# This file controls how Fivetran runs your transformation scripts. 
# For each transform, include the name of the file, what type of trigger, and trigger details. 
# Trigger options are 1. table (transformation will run when fresh data arrives from Fivetran) 
#                  or 2. interval (transformation will run on a set time schedule)
# Use three dashes (“---”) to separate transform configurations
# See examples below

# if you are triggering based on blah then use this
# name: triggeredTransformation.sql #transformation file name goes here
# trigger: 
#   type: table 
#   tables: #list the tables that will trigger this transformation
#     - <schema>.<table>
#     - schema2.table2

####################################### OR ################################
# if you need to blah then blah
# ---

name: current_date_replacement.sql 
trigger: 
  type: interval
  interval: 5m #choose from 5m, 15m, 30m, 1h, 2h, 3h, 6h, 8h, 12h, 24h